### ISSUE TITLE
Separate Assumptions and Requirements

### ISSUE THREAD

**Issue by horazont** [cknoll/git-voting#2]
The Assumptions are the environment in which the system operates. Example: "$N < 100"

The Requirements are the things the system must enforce/provide. Example: "No user shall vote more than once."

By grouping both, you make it sound as if "No user shall vote more than once." is an *Assumption* and is not a property (supposed to be) protected by the scheme.

You may even go further and split Assumptions in *Environmental Assumptions* and *Entities*, where Entities describes the participants of the system (S1-S3, the Users) and their properties (Keys etc.).

**Comment by cknoll** [comment]
Good point. Tried to fix this in 66338c281a47834714f3500d98f54e32515037e7.
